### ISSUE TITLE
Fix text in packaging samples regarding the use of empty TTML documents

### ISSUE THREAD

**Issue by andreastai** [rbouqueau/TTML_in_MP4_DASH_statement#12]
The current text in https://github.com/rbouqueau/TTML_in_MP4_DASH_statement/wiki/ebuttd_in_isobmff_samples currently says:

> For the duration where no subtitle content is active the empty TTML document **needs to** be send.

But the relevant MPEG Spec 14496-30 does not mandate sending an empty TTML document, it is just an option. So this should change to 

>  For the duration where no subtitle content is active an empty TTML document **may be** sent.

**Comment by andreastai** [comment]
This now has been fixed. Thanks to @mikedo for spotting this.

**Comment by nigelmegitt** [comment]
In case anyone else goes round the same "huh?" loop as me looking for this fix, that the text that was fixed is in a wiki page rather than the main document in this repo, and GitHub doesn't easily expose wiki changes as commit references.
