### ISSUE TITLE
"TTML content does not usually have a fixed frame rate"

### ISSUE THREAD

**Issue by nigelmegitt** [rbouqueau/TTML_in_MP4_DASH_statement#5]
The phrase

> Since TTML content does not usually have a fixed frame rate

is confusing - TTML content either a) has a stated frame rate or b) does not use frame-based timing expressions. I think perhaps what we should say instead here is:

> Since TTML content does not have a constant rate of change

**Comment by rbouqueau** [comment]
Thank you :)

**Comment by nigelmegitt** [comment]
You're welcome!
