### ISSUE TITLE
Should we recommend that HTTP compression is used?

### ISSUE THREAD

**Issue by nigelmegitt** [rbouqueau/TTML_in_MP4_DASH_statement#6]
When we state that duplication of data should be avoided, that's true, however it's not a very strong technique for reducing the amount of data overall. We could alternatively recommend that CDNs make use of HTTP compression if data rates need to be managed down.

As a data point, if a strategy of 'a new segment or sample for every change in TTML content' is used, then it's very likely based on my measurements that every TTML document will be smaller than an ethernet frame. So compression doesn't really help. Accumulating TTML content over several seconds may make compression more worthwhile.

**Comment by cconcolato** [comment]
It might be interesting to indeed give some size and bitrate indications of typical TTML content: size (gzipped and not) for an entire program like a 2h movie, size (gzipped and not) for a typical segment size (e.g. HLS-like 10s and shorter), and associated bitrates. My guess is that it's going to be negligible compared to the video size anyway, so I'm not sure compression will be a big factor here.

**Comment by nigelmegitt** [comment]
I agree it will be negligible compared to the video size. There are a lot of variables to consider though and I'm not sure what "typical" TTML content is. The other comparison point is the size relative to bitmap subtitles - again I think it will be negligible in comparison.

**Comment by rbouqueau** [comment]
What do you think? Should we make a small paragraph about that in the document?

**Comment by nigelmegitt** [comment]
To give a data point, I recently created an EBU-TT-D document for a 90 minute programme/film and its size was just over 200kb. This fits with other experiments I've done in the past, which suggested that a 500kb max document size can cover most programmes, with programme duration needing to be measured in hours to exceed this.

When I gzip this file (i.e. the most likely form of http compression to be adopted) it becomes just over 32kb, so the compression ratio is ~6.5-7x for this file, which is perhaps typical for this kind of data (but I don't have enough data points to say that with any authority).

It's hard to quote numbers in the document because so much depends on the style of the content in the document, e.g. if there are a lot of cumulative subtitles they will take more data than block subtitles. However I guess that this amount of data is indeed negligible compared to the video size.

According to this [BBC iplayer bitrates](http://www.bbc.co.uk/rd/blog/2015/07/the-development-of-new-video-factory-profiles-for-bbc-iplayer) blog post the lowest bitrate audio and video profiles add up to 55kbps so our uncompressed 200kb subtitle file is about 4s of video + audio, which I calculate to be 0.07% of a 90 minute programme. Whereas at the highest bitrates the 200kb file is about 0.6 frames of video+audio, being about 0.0004% of the programme!

I think we're in "negligible" territory here either way.

In case anyone thinks there is any debate to be had here about storage, network and distribution costs I think it is worth adding a small paragraph to explain that this is not sensible.
